#server:
#  port: 8989
#
#spring:
#  application:
#    name: GATEWAY-SERVICE
#
#  cloud:
#    gateway:
#      routes:
#        - id: FlightMicroservices
#          uri: lb://FLIGHT-SERVICE
#          predicates:
#            - Path=/api/**
#       
#        - id: UserMicroServices
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/v1.0/flight/**
#       
#        - id: adminMicroservices
#          uri: lb://ADMIN-SERVICE
#          predicates:
#            - Path=/api/v1.0/flight/admin/**    
#            
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#
